var express = require('express');
var router = express.Router();
const NGO = require('../models/ngo');
const nodemailer = require('nodemailer');
const Feedback = require('../models/feedback');
const Help = require('../models/help');

/* GET users listing. */
router.get('/', (req,res,next)=>{
  NGO.find({})
        .then((users)=>{
            res.statusCode=200,
            res.setHeader('Content-Type','application/json');
            res.send(users);
        },(err)=>next(err))
            .catch((err)=>next(err));
});

router.get('/byAddress', (req,res,next)=>{
  //console.log('../..',req.query.address);
  NGO.find({address:req.query.address})
        .then((users)=>{
            console.log('//',users);
            res.statusCode=200,
            res.setHeader('Content-Type','application/json');
            res.send(users);
        },(err)=>next(err))
            .catch((err)=>next(err));
});

router.post('/signUp',(req,res,next)=>{
    NGO.create(req.body)
    .then((result)=>{
      res.statusCode = 200,
      res.send({'result':'success'});
    },(err)=>next(err))
      .catch((err)=>next(err));
});

router.post('/login',(req,res,next)=>{
    NGO.findOne(req.body)
    .then((result)=>{
      //console.log(result);
      if(result){
        res.statusCode = 200;
        res.send(result);
      }else{
        res.statusCode = 400;
        res.send({"result":"Invalid credentials"})
      }
    },(err)=>next(err))
      .catch((err)=>next(err));
});

router.get('/logout',(req,res,next)=>{
  res.statusCode = 200;
  res.send({'result':'Successfully logged out'});
});

router.post('/feedback',(req,res,next)=>{
  Feedback.create(req.body)
    .then((result)=>{
      console.log(result);
      res.statusCode = 200;
      res.send({'Result':'Successfully sent'});
    },(err)=>next(err))
      .catch((err)=>next(err));
});

router.post('/help',(req,res,next)=>{
  Help.create(req.body)
    .then((result)=>{
      console.log(result);
      res.statusCode = 200;
      res.send({'Result':'Successfully sent'});
    },(err)=>next(err))
      .catch((err)=>next(err));
});

router.get('/getFeedback',(req,res,next)=>{
  Feedback.find({ngoAddress:req.query.ngoAddress})
    .then((result)=>{
      console.log(result);
      res.statusCode = 200;
      res.send(result);
    },(err)=>next(err))
      .catch((err)=>next(err));
});

router.get('/getHelp',(req,res,next)=>{
  Help.find({ngoAddress:req.query.ngoAddress})
    .then((result)=>{
      console.log(result);
      res.statusCode = 200;
      res.send(result);
    },(err)=>next(err))
      .catch((err)=>next(err));
});


router.post('/sendMail',(req,res,next)=>{
  console.log("Into ngo/sendMail")
  try{
    var transport = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 587,
      auth: {
        user: 'manmathbhale315@gmail.com', //example of generated by Mailtrap 
        pass: 'Rohit4531' //example of generated by Mailtrap 
      }
    });
     
    var i,succesfullySent=[];
    for(i=0;i<req.body.length;i++){
      var mailOptions = {
        from: req.body[i].from,
        to: req.body[i].to,
        subject: 'Details Regarding Donations',
        text: req.body[i].ngo_name + ' has used '+req.body[i].amount+' from your donations to help '+req.body[i].reciever+'. Transaction id is '+req.body[i].transactionId
       
      };
       
      transport.sendMail(mailOptions, (error, info) => {
        if (error) {
          console.log(error);
        }else{
          
          succesfullySent.push(req.body[i].to);
          console.log(i,req.body.length);
          console.log('Email sent: ' + info.response);
          
        }
        
      });
    }
      
    
    res.statusCode = 200;
    res.send({'count':succesfullySent.length,'Addresses':succesfullySent});      
    

  }catch(err){
    res.statusCode = 400;
    res.send(err);
  }

});


module.exports = router;

